! /etc/keepalived/keepalived.conf -- 172.21.129.138 (BACKUP, takes over VIP
! only if 172.21.129.16 or its nginx goes down)

global_defs {
    enable_script_security
    script_user root
}

vrrp_script chk_nginx {
    script "/etc/keepalived/check_nginx.sh"
    interval 2
    fall 2
    rise 2
    weight -60
}

vrrp_instance SSH_LB {
    state BACKUP
    interface eno1
    virtual_router_id 51
    priority 100
    advert_int 1
    preempt

    authentication {
        auth_type PASS
        auth_pass sshlb26
    }

    virtual_ipaddress {
        172.21.129.200/20 dev eno1
    }

    track_script {
        chk_nginx
    }
}
